name: x86-ubuntu

on:
  workflow_dispatch:
  push:
    branches: [ "master", "dev", "sdr-1.0.4" ]

env:
  BUILD_TYPE: Release
  BUILD_DIR: build
  PACKAGE_DIR: build-out

jobs:
  skip_check:
    continue-on-error: false
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: 'same_content'
        cancel_others: 'true'
        skip_after_successful_duplicate: 'true'
        paths_ignore: '["**/README.md", "**/docs/**", "**/LICENSE.txt", "vcpkg.json", "toolchains/windows/*", "toolchains/macos/*"]'
        do_not_skip: '["workflow_dispatch", "schedule"]'

  build:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive 

    - name: Install packages
      run: |
        sudo apt-get update 
        ./toolchains/ubuntu/install_packages.sh

    - name: Configure CMake
      run: cmake . -B ${{github.workspace}}/${{env.BUILD_DIR}} --preset gcc -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/${{env.BUILD_DIR}} --target dab_plugin

    - name: Create package
      run: |
        mkdir -p ${{env.PACKAGE_DIR}} 
        cp ${{env.BUILD_DIR}}/src/*.so ${{env.PACKAGE_DIR}}/
        cp README.md ${{env.PACKAGE_DIR}}/

    - name: Upload files (Release)
      uses: actions/upload-artifact@v4
      with:
        name: sdrpp_dab_radio_plugin_ubuntu
        path: ${{github.workspace}}/${{env.PACKAGE_DIR}}
    
